import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import List
from stock_scanner.config import config
from stock_scanner.models import StockResult
from stock_scanner.utils.logger import get_logger

logger = get_logger(__name__)

class EmailClient:
    def __init__(self):
        self.sender_email = config.EMAIL_ADDRESS
        self.sender_password = config.EMAIL_PASSWORD
        self.recipient_email = config.EMAIL_RECIPIENT

    def send_report(self, results: List[StockResult], csv_filename: str):
        """Sends an HTML report of the scan results."""
        if not all([self.sender_email, self.sender_password, self.recipient_email]):
            logger.warning("Email credentials or recipient not set. Skipping email.")
            return

        if not results:
            logger.info("No results to email.")
            return

        # Prepare HTML table and detailed reports
        table_rows = ""
        detailed_reports_html = ""
        
        for r in results:
            sentiment_label = "Negative" if r.news_sentiment.is_negative else "Neutral/Positive"
            sentiment_color = "#dc3545" if r.news_sentiment.is_negative else "#28a745"
            
            table_rows += f"""
            <tr>
                <td><b>{r.candidate.symbol}</b></td>
                <td>${r.candidate.price}</td>
                <td>{r.volume_analysis.ratio:.2f}x</td>
                <td>{r.analyst_rating.upside_percent:.1f}%</td>
                <td style="color: {sentiment_color};">{sentiment_label}</td>
            </tr>
            """
            
            # Build detailed report section if content exists
            if r.reports and (r.reports.company_report or r.reports.ceo_report):
                report_section = f"""
                <div class="report-block">
                    <h3>{r.candidate.company_name} ({r.candidate.symbol})</h3>
                    <p><b>Analyst Reasoning:</b> {r.news_sentiment.summary}</p>
                """
                
                if r.reports.company_report:
                    # Basic markdown conversion (line breaks to <br>)
                    company_clean = r.reports.company_report.replace('\n', '<br>')
                    report_section += f"""
                    <div class="report-content">
                        <h4>Company Analysis</h4>
                        <p>{company_clean}</p>
                    </div>
                    """
                    
                if r.reports.ceo_report:
                    ceo_clean = r.reports.ceo_report.replace('\n', '<br>')
                    report_section += f"""
                    <div class="report-content">
                        <h4>CEO Report</h4>
                        <p>{ceo_clean}</p>
                    </div>
                    """
                
                report_section += "</div><hr>"
                detailed_reports_html += report_section

        subject = f"🚀 Stock Scan Results (v2) - {datetime.now().strftime('%Y-%m-%d %H:%M')}"
        
        body = f"""
        <html>
          <head>
            <style>
              body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
              table {{ border-collapse: collapse; width: 100%; margin-bottom: 20px; }}
              th, td {{ text-align: left; padding: 12px; border: 1px solid #ddd; }}
              th {{ background-color: #007bff; color: white; }}
              tr:nth-child(even) {{ background-color: #f8f9fa; }}
              .report-block {{ background-color: #ffffff; padding: 15px; border-radius: 5px; }}
              .report-content {{ margin-top: 10px; padding: 10px; border-left: 4px solid #007bff; background-color: #f1f8ff; }}
              h2 {{ color: #007bff; border-bottom: 2px solid #007bff; padding-bottom: 10px; }}
              h3 {{ color: #333; margin-top: 0; }}
              h4 {{ color: #007bff; margin-bottom: 5px; }}
            </style>
          </head>
          <body>
            <h2>High Potential Candidates (LangGraph)</h2>
            <p>Found {len(results)} stocks matching criteria.</p>
            
            <table>
                <thead>
                    <tr>
                        <th>Symbol</th>
                        <th>Price</th>
                        <th>Vol Ratio</th>
                        <th>Upside</th>
                        <th>Sentiment</th>
                    </tr>
                </thead>
                <tbody>
                    {table_rows}
                </tbody>
            </table>

            {f"<h2>Detailed Analysis Report</h2>{detailed_reports_html}" if detailed_reports_html else ""}
            
            <p><em>Generated by Stock Scanner v2</em></p>
          </body>
        </html>
        """

        msg = MIMEMultipart()
        msg['From'] = self.sender_email
        msg['To'] = self.recipient_email
        msg['Subject'] = subject
        msg.attach(MIMEText(body, 'html'))

        try:
            # Using SMTP_SSL for Gmail
            with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
                server.login(self.sender_email, self.sender_password)
                server.send_message(msg)
            logger.info(f"Report email sent successfully to {self.recipient_email}!")
        except Exception as e:
            logger.error(f"Failed to send email: {e}")
